use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# DmlWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :dml, DmlWeb.Endpoint,
  load_from_system_env: true,
  http: [port: {:system, "PORT"}],
  url: [host: "localhost", port: {:system, "PORT"}],
  # cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: Map.fetch!(System.get_env(), "SECRET_KEY_BASE"),
  code_reloader: false,
  server: true,
  root: '.',
  version: Application.spec(:dml, :vsn)

config :dml, Dml.Repo,
  url: System.get_env("DATABASE_URL"),
  ssl: true,
  pool_size: Map.get(System.get_env(), "DATABASE_POOL_SIZE", 1)

# Do not print debug messages in production
config :logger, level: :info

# Guardian config
config :dml, Dml.Guardian,
  issuer: "DML",
  secret_key: Map.fetch!(System.get_env(), "SECRET_KEY_BASE")

# JSONAPI
config :jsonapi,
  host: "dml-api.dev.kyokan.io",
  scheme: "https"

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :dml, DmlWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :dml, DmlWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :dml, DmlWeb.Endpoint, server: true
#

config :dml, Dml.Accounts.GoogleClient,
  client_id: System.get_env("GOOGLE_CLIENT_ID"),
  client_secret: System.get_env("GOOGLE_CLIENT_SECRET"),
  redirect_uri: System.get_env("GOOGLE_REDIRECT_URI")

config :dml, Dml.Accounts.FacebookClient,
  client_id: System.get_env("FACEBOOK_APP_ID"),
  client_secret: System.get_env("FACEBOOK_APP_SECRET"),
  redirect_uri: System.get_env("FACEBOOK_REDIRECT_URI")

# Arc
config :arc,
  storage: Arc.Storage.S3,
  bucket: System.get_env("S3_BUCKET")

# ExAWS
config :ex_aws,
  region: System.get_env("AWS_REGION")

# Finally import the config/prod.secret.exs which should be versioned separately.
# import_config "prod.secret.exs"
